name: CI with Test Generation

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  generate_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright==1.55.0 requests pytest
        playwright install chromium

    - name: Generate unit tests via openrouter AI
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      run: |
        python generate_tests.py

    - name: Run regression tests
      run: |
        pytest --maxfail=3 --disable-warnings -q
