name: Test Generation and Validation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate tests with fallback
      run: |
        echo "Generating tests with optimized system..."
        python smart_test_generator.py
      continue-on-error: true

    - name: Alternative test generation if API fails
      run: |
        echo "Running alternative test generation..."
        python output_capture.py
      continue-on-error: true

    - name: Run all tests
      run: |
        echo "Running all tests after test generation..."
        python -m pytest test_generated.py -v --tb=short

    - name: Commit updated tests
      run: |
        echo "Committing updated test_generated.py to repository..."
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add test_generated.py
        git commit -m "Update generated tests" || echo "No changes to commit"
      continue-on-error: true

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          test_generated.py
          *.xml
          *.html